name: google_api_headers
description: A Flutter plugin for getting the headers required to call Google APIs with an app restricted API key
version: 5.1.0
homepage: https://github.com/zeshuaro/google_api_headers

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0

dev_dependencies:
  build_runner: 2.10.4
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: io.github.zeshuaro.google_api_headers
        pluginClass: GoogleApiHeadersPlugin
