name: google_api_headers
description: A Flutter plugin for getting the headers required to call Google APIs with an app restricted API key
version: 4.5.2
homepage: https://github.com/zeshuaro/google_api_headers

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.3"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.0

dev_dependencies:
  build_runner: 2.4.15
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: io.github.zeshuaro.google_api_headers
        pluginClass: GoogleApiHeadersPlugin
